name: example
description: "Example application for the "
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.2

dependencies:
  flutter:
    sdk: flutter
  auto_scrolling:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
