name: auto_scrolling
description: "Enables auto scrolling in a scrollable (ListView, GridView, etc.) by using tertiary mouse button (mouse wheel click)."
topics:
  - scroll
  - scrolling
  - autoscroll
  - mouse

homepage: https://keepascent.com
repository: https://github.com/KeepAscent/auto_scrolling
issue_tracker: https://github.com/KeepAscent/auto_scrolling/issues

version: 0.4.0

environment:
  sdk: ^3.0.0
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
