name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  flutter_version: "3.29.0"
  flutter_channel: "stable"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get --no-example

      - name: Flutter Doctor
        run: flutter doctor --verbose

      - name: Analyze
        run: flutter analyze

      - name: Check code formatting
        run: flutter format --set-exit-if-changed --dry-run .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and generate coverage
        run: flutter test --coverage -r expanded .

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          file: coverage/lcov.info
