name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  flutter_version: "3.29.0"
  flutter_channel: "stable"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code from repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Remove example/ directory
        run: rm -rf example/

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run analyze
        run: flutter analyze .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}

      - name: Remove example/ directory
        run: rm -rf example/

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and generate coverage
        run: flutter test --coverage -r expanded .

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          file: coverage/lcov.info
